// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: satcfdi/v1/service.proto

package satcfdiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/herramientassatgobmx/go-satcfdi/proto/satcfdi/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SATServiceName is the fully-qualified name of the SATService service.
	SATServiceName = "satcfdi.v1.SATService"
	// SATFlowServiceName is the fully-qualified name of the SATFlowService service.
	SATFlowServiceName = "satcfdi.v1.SATFlowService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SATServiceAuthenticateProcedure is the fully-qualified name of the SATService's Authenticate RPC.
	SATServiceAuthenticateProcedure = "/satcfdi.v1.SATService/Authenticate"
	// SATServiceConsultDownloadProcedure is the fully-qualified name of the SATService's
	// ConsultDownload RPC.
	SATServiceConsultDownloadProcedure = "/satcfdi.v1.SATService/ConsultDownload"
	// SATServiceVerifyDownloadProcedure is the fully-qualified name of the SATService's VerifyDownload
	// RPC.
	SATServiceVerifyDownloadProcedure = "/satcfdi.v1.SATService/VerifyDownload"
	// SATServiceDownloadPackageProcedure is the fully-qualified name of the SATService's
	// DownloadPackage RPC.
	SATServiceDownloadPackageProcedure = "/satcfdi.v1.SATService/DownloadPackage"
	// SATServiceStreamDownloadPackageProcedure is the fully-qualified name of the SATService's
	// StreamDownloadPackage RPC.
	SATServiceStreamDownloadPackageProcedure = "/satcfdi.v1.SATService/StreamDownloadPackage"
	// SATServiceValidateCfdiProcedure is the fully-qualified name of the SATService's ValidateCfdi RPC.
	SATServiceValidateCfdiProcedure = "/satcfdi.v1.SATService/ValidateCfdi"
	// SATFlowServiceRunDownloadFlowProcedure is the fully-qualified name of the SATFlowService's
	// RunDownloadFlow RPC.
	SATFlowServiceRunDownloadFlowProcedure = "/satcfdi.v1.SATFlowService/RunDownloadFlow"
)

// SATServiceClient is a client for the satcfdi.v1.SATService service.
type SATServiceClient interface {
	Authenticate(context.Context, *connect.Request[v1.AuthenticateRequest]) (*connect.Response[v1.AuthenticateResponse], error)
	ConsultDownload(context.Context, *connect.Request[v1.ConsultDownloadRequest]) (*connect.Response[v1.ConsultDownloadResponse], error)
	VerifyDownload(context.Context, *connect.Request[v1.VerifyDownloadRequest]) (*connect.Response[v1.VerifyDownloadResponse], error)
	// DownloadPackage is kept for compatibility and small payloads. Large
	// packages should use StreamDownloadPackage instead.
	DownloadPackage(context.Context, *connect.Request[v1.DownloadPackageRequest]) (*connect.Response[v1.DownloadPackageResponse], error)
	StreamDownloadPackage(context.Context, *connect.Request[v1.StreamDownloadPackageRequest]) (*connect.ServerStreamForClient[v1.StreamDownloadPackageResponse], error)
	ValidateCfdi(context.Context, *connect.Request[v1.ValidateCfdiRequest]) (*connect.Response[v1.ValidateCfdiResponse], error)
}

// NewSATServiceClient constructs a client for the satcfdi.v1.SATService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSATServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SATServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sATServiceMethods := v1.File_satcfdi_v1_service_proto.Services().ByName("SATService").Methods()
	return &sATServiceClient{
		authenticate: connect.NewClient[v1.AuthenticateRequest, v1.AuthenticateResponse](
			httpClient,
			baseURL+SATServiceAuthenticateProcedure,
			connect.WithSchema(sATServiceMethods.ByName("Authenticate")),
			connect.WithClientOptions(opts...),
		),
		consultDownload: connect.NewClient[v1.ConsultDownloadRequest, v1.ConsultDownloadResponse](
			httpClient,
			baseURL+SATServiceConsultDownloadProcedure,
			connect.WithSchema(sATServiceMethods.ByName("ConsultDownload")),
			connect.WithClientOptions(opts...),
		),
		verifyDownload: connect.NewClient[v1.VerifyDownloadRequest, v1.VerifyDownloadResponse](
			httpClient,
			baseURL+SATServiceVerifyDownloadProcedure,
			connect.WithSchema(sATServiceMethods.ByName("VerifyDownload")),
			connect.WithClientOptions(opts...),
		),
		downloadPackage: connect.NewClient[v1.DownloadPackageRequest, v1.DownloadPackageResponse](
			httpClient,
			baseURL+SATServiceDownloadPackageProcedure,
			connect.WithSchema(sATServiceMethods.ByName("DownloadPackage")),
			connect.WithClientOptions(opts...),
		),
		streamDownloadPackage: connect.NewClient[v1.StreamDownloadPackageRequest, v1.StreamDownloadPackageResponse](
			httpClient,
			baseURL+SATServiceStreamDownloadPackageProcedure,
			connect.WithSchema(sATServiceMethods.ByName("StreamDownloadPackage")),
			connect.WithClientOptions(opts...),
		),
		validateCfdi: connect.NewClient[v1.ValidateCfdiRequest, v1.ValidateCfdiResponse](
			httpClient,
			baseURL+SATServiceValidateCfdiProcedure,
			connect.WithSchema(sATServiceMethods.ByName("ValidateCfdi")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sATServiceClient implements SATServiceClient.
type sATServiceClient struct {
	authenticate          *connect.Client[v1.AuthenticateRequest, v1.AuthenticateResponse]
	consultDownload       *connect.Client[v1.ConsultDownloadRequest, v1.ConsultDownloadResponse]
	verifyDownload        *connect.Client[v1.VerifyDownloadRequest, v1.VerifyDownloadResponse]
	downloadPackage       *connect.Client[v1.DownloadPackageRequest, v1.DownloadPackageResponse]
	streamDownloadPackage *connect.Client[v1.StreamDownloadPackageRequest, v1.StreamDownloadPackageResponse]
	validateCfdi          *connect.Client[v1.ValidateCfdiRequest, v1.ValidateCfdiResponse]
}

// Authenticate calls satcfdi.v1.SATService.Authenticate.
func (c *sATServiceClient) Authenticate(ctx context.Context, req *connect.Request[v1.AuthenticateRequest]) (*connect.Response[v1.AuthenticateResponse], error) {
	return c.authenticate.CallUnary(ctx, req)
}

// ConsultDownload calls satcfdi.v1.SATService.ConsultDownload.
func (c *sATServiceClient) ConsultDownload(ctx context.Context, req *connect.Request[v1.ConsultDownloadRequest]) (*connect.Response[v1.ConsultDownloadResponse], error) {
	return c.consultDownload.CallUnary(ctx, req)
}

// VerifyDownload calls satcfdi.v1.SATService.VerifyDownload.
func (c *sATServiceClient) VerifyDownload(ctx context.Context, req *connect.Request[v1.VerifyDownloadRequest]) (*connect.Response[v1.VerifyDownloadResponse], error) {
	return c.verifyDownload.CallUnary(ctx, req)
}

// DownloadPackage calls satcfdi.v1.SATService.DownloadPackage.
func (c *sATServiceClient) DownloadPackage(ctx context.Context, req *connect.Request[v1.DownloadPackageRequest]) (*connect.Response[v1.DownloadPackageResponse], error) {
	return c.downloadPackage.CallUnary(ctx, req)
}

// StreamDownloadPackage calls satcfdi.v1.SATService.StreamDownloadPackage.
func (c *sATServiceClient) StreamDownloadPackage(ctx context.Context, req *connect.Request[v1.StreamDownloadPackageRequest]) (*connect.ServerStreamForClient[v1.StreamDownloadPackageResponse], error) {
	return c.streamDownloadPackage.CallServerStream(ctx, req)
}

// ValidateCfdi calls satcfdi.v1.SATService.ValidateCfdi.
func (c *sATServiceClient) ValidateCfdi(ctx context.Context, req *connect.Request[v1.ValidateCfdiRequest]) (*connect.Response[v1.ValidateCfdiResponse], error) {
	return c.validateCfdi.CallUnary(ctx, req)
}

// SATServiceHandler is an implementation of the satcfdi.v1.SATService service.
type SATServiceHandler interface {
	Authenticate(context.Context, *connect.Request[v1.AuthenticateRequest]) (*connect.Response[v1.AuthenticateResponse], error)
	ConsultDownload(context.Context, *connect.Request[v1.ConsultDownloadRequest]) (*connect.Response[v1.ConsultDownloadResponse], error)
	VerifyDownload(context.Context, *connect.Request[v1.VerifyDownloadRequest]) (*connect.Response[v1.VerifyDownloadResponse], error)
	// DownloadPackage is kept for compatibility and small payloads. Large
	// packages should use StreamDownloadPackage instead.
	DownloadPackage(context.Context, *connect.Request[v1.DownloadPackageRequest]) (*connect.Response[v1.DownloadPackageResponse], error)
	StreamDownloadPackage(context.Context, *connect.Request[v1.StreamDownloadPackageRequest], *connect.ServerStream[v1.StreamDownloadPackageResponse]) error
	ValidateCfdi(context.Context, *connect.Request[v1.ValidateCfdiRequest]) (*connect.Response[v1.ValidateCfdiResponse], error)
}

// NewSATServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSATServiceHandler(svc SATServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sATServiceMethods := v1.File_satcfdi_v1_service_proto.Services().ByName("SATService").Methods()
	sATServiceAuthenticateHandler := connect.NewUnaryHandler(
		SATServiceAuthenticateProcedure,
		svc.Authenticate,
		connect.WithSchema(sATServiceMethods.ByName("Authenticate")),
		connect.WithHandlerOptions(opts...),
	)
	sATServiceConsultDownloadHandler := connect.NewUnaryHandler(
		SATServiceConsultDownloadProcedure,
		svc.ConsultDownload,
		connect.WithSchema(sATServiceMethods.ByName("ConsultDownload")),
		connect.WithHandlerOptions(opts...),
	)
	sATServiceVerifyDownloadHandler := connect.NewUnaryHandler(
		SATServiceVerifyDownloadProcedure,
		svc.VerifyDownload,
		connect.WithSchema(sATServiceMethods.ByName("VerifyDownload")),
		connect.WithHandlerOptions(opts...),
	)
	sATServiceDownloadPackageHandler := connect.NewUnaryHandler(
		SATServiceDownloadPackageProcedure,
		svc.DownloadPackage,
		connect.WithSchema(sATServiceMethods.ByName("DownloadPackage")),
		connect.WithHandlerOptions(opts...),
	)
	sATServiceStreamDownloadPackageHandler := connect.NewServerStreamHandler(
		SATServiceStreamDownloadPackageProcedure,
		svc.StreamDownloadPackage,
		connect.WithSchema(sATServiceMethods.ByName("StreamDownloadPackage")),
		connect.WithHandlerOptions(opts...),
	)
	sATServiceValidateCfdiHandler := connect.NewUnaryHandler(
		SATServiceValidateCfdiProcedure,
		svc.ValidateCfdi,
		connect.WithSchema(sATServiceMethods.ByName("ValidateCfdi")),
		connect.WithHandlerOptions(opts...),
	)
	return "/satcfdi.v1.SATService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SATServiceAuthenticateProcedure:
			sATServiceAuthenticateHandler.ServeHTTP(w, r)
		case SATServiceConsultDownloadProcedure:
			sATServiceConsultDownloadHandler.ServeHTTP(w, r)
		case SATServiceVerifyDownloadProcedure:
			sATServiceVerifyDownloadHandler.ServeHTTP(w, r)
		case SATServiceDownloadPackageProcedure:
			sATServiceDownloadPackageHandler.ServeHTTP(w, r)
		case SATServiceStreamDownloadPackageProcedure:
			sATServiceStreamDownloadPackageHandler.ServeHTTP(w, r)
		case SATServiceValidateCfdiProcedure:
			sATServiceValidateCfdiHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSATServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSATServiceHandler struct{}

func (UnimplementedSATServiceHandler) Authenticate(context.Context, *connect.Request[v1.AuthenticateRequest]) (*connect.Response[v1.AuthenticateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("satcfdi.v1.SATService.Authenticate is not implemented"))
}

func (UnimplementedSATServiceHandler) ConsultDownload(context.Context, *connect.Request[v1.ConsultDownloadRequest]) (*connect.Response[v1.ConsultDownloadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("satcfdi.v1.SATService.ConsultDownload is not implemented"))
}

func (UnimplementedSATServiceHandler) VerifyDownload(context.Context, *connect.Request[v1.VerifyDownloadRequest]) (*connect.Response[v1.VerifyDownloadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("satcfdi.v1.SATService.VerifyDownload is not implemented"))
}

func (UnimplementedSATServiceHandler) DownloadPackage(context.Context, *connect.Request[v1.DownloadPackageRequest]) (*connect.Response[v1.DownloadPackageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("satcfdi.v1.SATService.DownloadPackage is not implemented"))
}

func (UnimplementedSATServiceHandler) StreamDownloadPackage(context.Context, *connect.Request[v1.StreamDownloadPackageRequest], *connect.ServerStream[v1.StreamDownloadPackageResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("satcfdi.v1.SATService.StreamDownloadPackage is not implemented"))
}

func (UnimplementedSATServiceHandler) ValidateCfdi(context.Context, *connect.Request[v1.ValidateCfdiRequest]) (*connect.Response[v1.ValidateCfdiResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("satcfdi.v1.SATService.ValidateCfdi is not implemented"))
}

// SATFlowServiceClient is a client for the satcfdi.v1.SATFlowService service.
type SATFlowServiceClient interface {
	RunDownloadFlow(context.Context, *connect.Request[v1.RunDownloadFlowRequest]) (*connect.Response[v1.RunDownloadFlowResponse], error)
}

// NewSATFlowServiceClient constructs a client for the satcfdi.v1.SATFlowService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSATFlowServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SATFlowServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sATFlowServiceMethods := v1.File_satcfdi_v1_service_proto.Services().ByName("SATFlowService").Methods()
	return &sATFlowServiceClient{
		runDownloadFlow: connect.NewClient[v1.RunDownloadFlowRequest, v1.RunDownloadFlowResponse](
			httpClient,
			baseURL+SATFlowServiceRunDownloadFlowProcedure,
			connect.WithSchema(sATFlowServiceMethods.ByName("RunDownloadFlow")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sATFlowServiceClient implements SATFlowServiceClient.
type sATFlowServiceClient struct {
	runDownloadFlow *connect.Client[v1.RunDownloadFlowRequest, v1.RunDownloadFlowResponse]
}

// RunDownloadFlow calls satcfdi.v1.SATFlowService.RunDownloadFlow.
func (c *sATFlowServiceClient) RunDownloadFlow(ctx context.Context, req *connect.Request[v1.RunDownloadFlowRequest]) (*connect.Response[v1.RunDownloadFlowResponse], error) {
	return c.runDownloadFlow.CallUnary(ctx, req)
}

// SATFlowServiceHandler is an implementation of the satcfdi.v1.SATFlowService service.
type SATFlowServiceHandler interface {
	RunDownloadFlow(context.Context, *connect.Request[v1.RunDownloadFlowRequest]) (*connect.Response[v1.RunDownloadFlowResponse], error)
}

// NewSATFlowServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSATFlowServiceHandler(svc SATFlowServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sATFlowServiceMethods := v1.File_satcfdi_v1_service_proto.Services().ByName("SATFlowService").Methods()
	sATFlowServiceRunDownloadFlowHandler := connect.NewUnaryHandler(
		SATFlowServiceRunDownloadFlowProcedure,
		svc.RunDownloadFlow,
		connect.WithSchema(sATFlowServiceMethods.ByName("RunDownloadFlow")),
		connect.WithHandlerOptions(opts...),
	)
	return "/satcfdi.v1.SATFlowService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SATFlowServiceRunDownloadFlowProcedure:
			sATFlowServiceRunDownloadFlowHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSATFlowServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSATFlowServiceHandler struct{}

func (UnimplementedSATFlowServiceHandler) RunDownloadFlow(context.Context, *connect.Request[v1.RunDownloadFlowRequest]) (*connect.Response[v1.RunDownloadFlowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("satcfdi.v1.SATFlowService.RunDownloadFlow is not implemented"))
}
