// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: satcfdi/v1/service.proto

package satcfdiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadType int32

const (
	DownloadType_DOWNLOAD_TYPE_UNSPECIFIED DownloadType = 0
	DownloadType_DOWNLOAD_TYPE_RECIBIDOS   DownloadType = 1
	DownloadType_DOWNLOAD_TYPE_EMITIDOS    DownloadType = 2
)

// Enum value maps for DownloadType.
var (
	DownloadType_name = map[int32]string{
		0: "DOWNLOAD_TYPE_UNSPECIFIED",
		1: "DOWNLOAD_TYPE_RECIBIDOS",
		2: "DOWNLOAD_TYPE_EMITIDOS",
	}
	DownloadType_value = map[string]int32{
		"DOWNLOAD_TYPE_UNSPECIFIED": 0,
		"DOWNLOAD_TYPE_RECIBIDOS":   1,
		"DOWNLOAD_TYPE_EMITIDOS":    2,
	}
)

func (x DownloadType) Enum() *DownloadType {
	p := new(DownloadType)
	*p = x
	return p
}

func (x DownloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DownloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_satcfdi_v1_service_proto_enumTypes[0].Descriptor()
}

func (DownloadType) Type() protoreflect.EnumType {
	return &file_satcfdi_v1_service_proto_enumTypes[0]
}

func (x DownloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DownloadType.Descriptor instead.
func (DownloadType) EnumDescriptor() ([]byte, []int) {
	return file_satcfdi_v1_service_proto_rawDescGZIP(), []int{0}
}

type QueryType int32

const (
	QueryType_QUERY_TYPE_UNSPECIFIED QueryType = 0
	QueryType_QUERY_TYPE_CFDI        QueryType = 1
	QueryType_QUERY_TYPE_METADATA    QueryType = 2
)

// Enum value maps for QueryType.
var (
	QueryType_name = map[int32]string{
		0: "QUERY_TYPE_UNSPECIFIED",
		1: "QUERY_TYPE_CFDI",
		2: "QUERY_TYPE_METADATA",
	}
	QueryType_value = map[string]int32{
		"QUERY_TYPE_UNSPECIFIED": 0,
		"QUERY_TYPE_CFDI":        1,
		"QUERY_TYPE_METADATA":    2,
	}
)

func (x QueryType) Enum() *QueryType {
	p := new(QueryType)
	*p = x
	return p
}

func (x QueryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryType) Descriptor() protoreflect.EnumDescriptor {
	return file_satcfdi_v1_service_proto_enumTypes[1].Descriptor()
}

func (QueryType) Type() protoreflect.EnumType {
	return &file_satcfdi_v1_service_proto_enumTypes[1]
}

func (x QueryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryType.Descriptor instead.
func (QueryType) EnumDescriptor() ([]byte, []int) {
	return file_satcfdi_v1_service_proto_rawDescGZIP(), []int{1}
}

type InvoiceStatus int32

const (
	InvoiceStatus_INVOICE_STATUS_UNSPECIFIED InvoiceStatus = 0
	InvoiceStatus_INVOICE_STATUS_ALL         InvoiceStatus = 1
	InvoiceStatus_INVOICE_STATUS_VIGENTE     InvoiceStatus = 2
	InvoiceStatus_INVOICE_STATUS_CANCELADO   InvoiceStatus = 3
)

// Enum value maps for InvoiceStatus.
var (
	InvoiceStatus_name = map[int32]string{
		0: "INVOICE_STATUS_UNSPECIFIED",
		1: "INVOICE_STATUS_ALL",
		2: "INVOICE_STATUS_VIGENTE",
		3: "INVOICE_STATUS_CANCELADO",
	}
	InvoiceStatus_value = map[string]int32{
		"INVOICE_STATUS_UNSPECIFIED": 0,
		"INVOICE_STATUS_ALL":         1,
		"INVOICE_STATUS_VIGENTE":     2,
		"INVOICE_STATUS_CANCELADO":   3,
	}
)

func (x InvoiceStatus) Enum() *InvoiceStatus {
	p := new(InvoiceStatus)
	*p = x
	return p
}

func (x InvoiceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvoiceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_satcfdi_v1_service_proto_enumTypes[2].Descriptor()
}

func (InvoiceStatus) Type() protoreflect.EnumType {
	return &file_satcfdi_v1_service_proto_enumTypes[2]
}

func (x InvoiceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvoiceStatus.Descriptor instead.
func (InvoiceStatus) EnumDescriptor() ([]byte, []int) {
	return file_satcfdi_v1_service_proto_rawDescGZIP(), []int{2}
}

// raw_request_status preserves the SAT numeric status code when clients need
// the original value. The enum remains stable for protobuf consumers.
type DownloadRequestStatus int32

const (
	DownloadRequestStatus_DOWNLOAD_REQUEST_STATUS_UNSPECIFIED   DownloadRequestStatus = 0
	DownloadRequestStatus_DOWNLOAD_REQUEST_STATUS_ACCEPTED      DownloadRequestStatus = 1
	DownloadRequestStatus_DOWNLOAD_REQUEST_STATUS_IN_PROGRESS   DownloadRequestStatus = 2
	DownloadRequestStatus_DOWNLOAD_REQUEST_STATUS_FINISHED      DownloadRequestStatus = 3
	DownloadRequestStatus_DOWNLOAD_REQUEST_STATUS_ERROR         DownloadRequestStatus = 4
	DownloadRequestStatus_DOWNLOAD_REQUEST_STATUS_REJECTED      DownloadRequestStatus = 5
	DownloadRequestStatus_DOWNLOAD_REQUEST_STATUS_EXPIRED       DownloadRequestStatus = 6
	DownloadRequestStatus_DOWNLOAD_REQUEST_STATUS_TOKEN_INVALID DownloadRequestStatus = 7
)

// Enum value maps for DownloadRequestStatus.
var (
	DownloadRequestStatus_name = map[int32]string{
		0: "DOWNLOAD_REQUEST_STATUS_UNSPECIFIED",
		1: "DOWNLOAD_REQUEST_STATUS_ACCEPTED",
		2: "DOWNLOAD_REQUEST_STATUS_IN_PROGRESS",
		3: "DOWNLOAD_REQUEST_STATUS_FINISHED",
		4: "DOWNLOAD_REQUEST_STATUS_ERROR",
		5: "DOWNLOAD_REQUEST_STATUS_REJECTED",
		6: "DOWNLOAD_REQUEST_STATUS_EXPIRED",
		7: "DOWNLOAD_REQUEST_STATUS_TOKEN_INVALID",
	}
	DownloadRequestStatus_value = map[string]int32{
		"DOWNLOAD_REQUEST_STATUS_UNSPECIFIED":   0,
		"DOWNLOAD_REQUEST_STATUS_ACCEPTED":      1,
		"DOWNLOAD_REQUEST_STATUS_IN_PROGRESS":   2,
		"DOWNLOAD_REQUEST_STATUS_FINISHED":      3,
		"DOWNLOAD_REQUEST_STATUS_ERROR":         4,
		"DOWNLOAD_REQUEST_STATUS_REJECTED":      5,
		"DOWNLOAD_REQUEST_STATUS_EXPIRED":       6,
		"DOWNLOAD_REQUEST_STATUS_TOKEN_INVALID": 7,
	}
)

func (x DownloadRequestStatus) Enum() *DownloadRequestStatus {
	p := new(DownloadRequestStatus)
	*p = x
	return p
}

func (x DownloadRequestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DownloadRequestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_satcfdi_v1_service_proto_enumTypes[3].Descriptor()
}

func (DownloadRequestStatus) Type() protoreflect.EnumType {
	return &file_satcfdi_v1_service_proto_enumTypes[3]
}

func (x DownloadRequestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DownloadRequestStatus.Descriptor instead.
func (DownloadRequestStatus) EnumDescriptor() ([]byte, []int) {
	return file_satcfdi_v1_service_proto_rawDescGZIP(), []int{3}
}

type ErrorCategory int32

const (
	ErrorCategory_ERROR_CATEGORY_UNSPECIFIED    ErrorCategory = 0
	ErrorCategory_ERROR_CATEGORY_VALIDATION     ErrorCategory = 1
	ErrorCategory_ERROR_CATEGORY_CREDENTIALS    ErrorCategory = 2
	ErrorCategory_ERROR_CATEGORY_AUTHENTICATION ErrorCategory = 3
	ErrorCategory_ERROR_CATEGORY_BUSINESS       ErrorCategory = 4
	ErrorCategory_ERROR_CATEGORY_SOAP           ErrorCategory = 5
	ErrorCategory_ERROR_CATEGORY_TRANSPORT      ErrorCategory = 6
	ErrorCategory_ERROR_CATEGORY_INTERNAL       ErrorCategory = 7
	ErrorCategory_ERROR_CATEGORY_TIMEOUT        ErrorCategory = 8
)

// Enum value maps for ErrorCategory.
var (
	ErrorCategory_name = map[int32]string{
		0: "ERROR_CATEGORY_UNSPECIFIED",
		1: "ERROR_CATEGORY_VALIDATION",
		2: "ERROR_CATEGORY_CREDENTIALS",
		3: "ERROR_CATEGORY_AUTHENTICATION",
		4: "ERROR_CATEGORY_BUSINESS",
		5: "ERROR_CATEGORY_SOAP",
		6: "ERROR_CATEGORY_TRANSPORT",
		7: "ERROR_CATEGORY_INTERNAL",
		8: "ERROR_CATEGORY_TIMEOUT",
	}
	ErrorCategory_value = map[string]int32{
		"ERROR_CATEGORY_UNSPECIFIED":    0,
		"ERROR_CATEGORY_VALIDATION":     1,
		"ERROR_CATEGORY_CREDENTIALS":    2,
		"ERROR_CATEGORY_AUTHENTICATION": 3,
		"ERROR_CATEGORY_BUSINESS":       4,
		"ERROR_CATEGORY_SOAP":           5,
		"ERROR_CATEGORY_TRANSPORT":      6,
		"ERROR_CATEGORY_INTERNAL":       7,
		"ERROR_CATEGORY_TIMEOUT":        8,
	}
)

func (x ErrorCategory) Enum() *ErrorCategory {
	p := new(ErrorCategory)
	*p = x
	return p
}

func (x ErrorCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_satcfdi_v1_service_proto_enumTypes[4].Descriptor()
}

func (ErrorCategory) Type() protoreflect.EnumType {
	return &file_satcfdi_v1_service_proto_enumTypes[4]
}

func (x ErrorCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCategory.Descriptor instead.
func (ErrorCategory) EnumDescriptor() ([]byte, []int) {
	return file_satcfdi_v1_service_proto_rawDescGZIP(), []int{4}
}

// SATCredentials contains the same DER inputs already accepted by sat.NewFiel.
type SATCredentials struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CertificateDer     []byte                 `protobuf:"bytes,1,opt,name=certificate_der,json=certificateDer,proto3" json:"certificate_der,omitempty"`
	PrivateKeyDer      []byte                 `protobuf:"bytes,2,opt,name=private_key_der,json=privateKeyDer,proto3" json:"private_key_der,omitempty"`
	PrivateKeyPassword string                 `protobuf:"bytes,3,opt,name=private_key_password,json=privateKeyPassword,proto3" json:"private_key_password,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SATCredentials) Reset() {
	*x = SATCredentials{}
	mi := &file_satcfdi_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SATCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SATCredentials) ProtoMessage() {}

func (x *SATCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_satcfdi_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SATCredentials.ProtoReflect.Descriptor instead.
func (*SATCredentials) Descriptor() ([]byte, []int) {
	return file_satcfdi_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *SATCredentials) GetCertificateDer() []byte {
	if x != nil {
		return x.CertificateDer
	}
	return nil
}

func (x *SATCredentials) GetPrivateKeyDer() []byte {
	if x != nil {
		return x.PrivateKeyDer
	}
	return nil
}

func (x *SATCredentials) GetPrivateKeyPassword() string {
	if x != nil {
		return x.PrivateKeyPassword
	}
	return ""
}

// CredentialRef identifies an external credential material reference resolved
// by the server. Exactly one of credentials or credential_ref must be set on
// signed requests.
type CredentialRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialRef) Reset() {
	*x = CredentialRef{}
	mi := &file_satcfdi_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialRef) ProtoMessage() {}

func (x *CredentialRef) ProtoReflect() protoreflect.Message {
	mi := &file_satcfdi_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialRef.ProtoReflect.Descriptor instead.
func (*CredentialRef) Descriptor() ([]byte, []int) {
	return file_satcfdi_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *CredentialRef) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CredentialRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ServiceErrorDetail is attached as a Connect/gRPC error detail to provide a
// stable machine-readable shape for SAT failures.
type ServiceErrorDetail struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Category          ErrorCategory          `protobuf:"varint,1,opt,name=category,proto3,enum=satcfdi.v1.ErrorCategory" json:"category,omitempty"`
	SatCode           string                 `protobuf:"bytes,2,opt,name=sat_code,json=satCode,proto3" json:"sat_code,omitempty"`
	SatMessage        string                 `protobuf:"bytes,3,opt,name=sat_message,json=satMessage,proto3" json:"sat_message,omitempty"`
	SoapHttpStatus    int32                  `protobuf:"varint,4,opt,name=soap_http_status,json=soapHttpStatus,proto3" json:"soap_http_status,omitempty"`
	SoapFaultString   string                 `protobuf:"bytes,5,opt,name=soap_fault_string,json=soapFaultString,proto3" json:"soap_fault_string,omitempty"`
	Retryable         bool                   `protobuf:"varint,6,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Operation         string                 `protobuf:"bytes,7,opt,name=operation,proto3" json:"operation,omitempty"`
	RequestId         string                 `protobuf:"bytes,8,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PackageId         string                 `protobuf:"bytes,9,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	SatStatusCode     string                 `protobuf:"bytes,10,opt,name=sat_status_code,json=satStatusCode,proto3" json:"sat_status_code,omitempty"`
	RequestStatusCode string                 `protobuf:"bytes,11,opt,name=request_status_code,json=requestStatusCode,proto3" json:"request_status_code,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ServiceErrorDetail) Reset() {
	*x = ServiceErrorDetail{}
	mi := &file_satcfdi_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceErrorDetail) ProtoMessage() {}

func (x *ServiceErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_satcfdi_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceErrorDetail.ProtoReflect.Descriptor instead.
func (*ServiceErrorDetail) Descriptor() ([]byte, []int) {
	return file_satcfdi_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceErrorDetail) GetCategory() ErrorCategory {
	if x != nil {
		return x.Category
	}
	return ErrorCategory_ERROR_CATEGORY_UNSPECIFIED
}

func (x *ServiceErrorDetail) GetSatCode() string {
	if x != nil {
		return x.SatCode
	}
	return ""
}

func (x *ServiceErrorDetail) GetSatMessage() string {
	if x != nil {
		return x.SatMessage
	}
	return ""
}

func (x *ServiceErrorDetail) GetSoapHttpStatus() int32 {
	if x != nil {
		return x.SoapHttpStatus
	}
	return 0
}

func (x *ServiceErrorDetail) GetSoapFaultString() string {
	if x != nil {
		return x.SoapFaultString
	}
	return ""
}

func (x *ServiceErrorDetail) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *ServiceErrorDetail) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ServiceErrorDetail) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ServiceErrorDetail) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *ServiceErrorDetail) GetSatStatusCode() string {
	if x != nil {
		return x.SatStatusCode
	}
	return ""
}

func (x *ServiceErrorDetail) GetRequestStatusCode() string {
	if x != nil {
		return x.RequestStatusCode
	}
	return ""
}

type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credentials   *SATCredentials        `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	CredentialRef *CredentialRef         `protobuf:"bytes,2,opt,name=credential_ref,json=credentialRef,proto3" json:"credential_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_satcfdi_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_satcfdi_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_satcfdi_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *AuthenticateRequest) GetCredentials() *SATCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *AuthenticateRequest) GetCredentialRef() *CredentialRef {
	if x != nil {
		return x.CredentialRef
	}
	return nil
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_satcfdi_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_satcfdi_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_satcfdi_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *AuthenticateResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ConsultDownloadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Credentials    *SATCredentials        `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	AccessToken    string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RfcSolicitante string                 `protobuf:"bytes,3,opt,name=rfc_solicitante,json=rfcSolicitante,proto3" json:"rfc_solicitante,omitempty"`
	FechaInicial   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=fecha_inicial,json=fechaInicial,proto3" json:"fecha_inicial,omitempty"`
	FechaFinal     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=fecha_final,json=fechaFinal,proto3" json:"fecha_final,omitempty"`
	DownloadType   DownloadType           `protobuf:"varint,6,opt,name=download_type,json=downloadType,proto3,enum=satcfdi.v1.DownloadType" json:"download_type,omitempty"`
	QueryType      QueryType              `protobuf:"varint,7,opt,name=query_type,json=queryType,proto3,enum=satcfdi.v1.QueryType" json:"query_type,omitempty"`
	CounterpartRfc []string               `protobuf:"bytes,8,rep,name=counterpart_rfc,json=counterpartRfc,proto3" json:"counterpart_rfc,omitempty"`
	InvoiceType    string                 `protobuf:"bytes,9,opt,name=invoice_type,json=invoiceType,proto3" json:"invoice_type,omitempty"`
	InvoiceStatus  InvoiceStatus          `protobuf:"varint,10,opt,name=invoice_status,json=invoiceStatus,proto3,enum=satcfdi.v1.InvoiceStatus" json:"invoice_status,omitempty"`
	ThirdPartyRfc  string                 `protobuf:"bytes,11,opt,name=third_party_rfc,json=thirdPartyRfc,proto3" json:"third_party_rfc,omitempty"`
	Complemento    string                 `protobuf:"bytes,12,opt,name=complemento,proto3" json:"complemento,omitempty"`
	Uuid           string                 `protobuf:"bytes,13,opt,name=uuid,proto3" json:"uuid,omitempty"`
	CredentialRef  *CredentialRef         `protobuf:"bytes,14,opt,name=credential_ref,json=credentialRef,proto3" json:"credential_ref,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConsultDownloadRequest) Reset() {
	*x = ConsultDownloadRequest{}
	mi := &file_satcfdi_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultDownloadRequest) ProtoMessage() {}

func (x *ConsultDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_satcfdi_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultDownloadRequest.ProtoReflect.Descriptor instead.
func (*ConsultDownloadRequest) Descriptor() ([]byte, []int) {
	return file_satcfdi_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *ConsultDownloadRequest) GetCredentials() *SATCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *ConsultDownloadRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *ConsultDownloadRequest) GetRfcSolicitante() string {
	if x != nil {
		return x.RfcSolicitante
	}
	return ""
}

func (x *ConsultDownloadRequest) GetFechaInicial() *timestamppb.Timestamp {
	if x != nil {
		return x.FechaInicial
	}
	return nil
}

func (x *ConsultDownloadRequest) GetFechaFinal() *timestamppb.Timestamp {
	if x != nil {
		return x.FechaFinal
	}
	return nil
}

func (x *ConsultDownloadRequest) GetDownloadType() DownloadType {
	if x != nil {
		return x.DownloadType
	}
	return DownloadType_DOWNLOAD_TYPE_UNSPECIFIED
}

func (x *ConsultDownloadRequest) GetQueryType() QueryType {
	if x != nil {
		return x.QueryType
	}
	return QueryType_QUERY_TYPE_UNSPECIFIED
}

func (x *ConsultDownloadRequest) GetCounterpartRfc() []string {
	if x != nil {
		return x.CounterpartRfc
	}
	return nil
}

func (x *ConsultDownloadRequest) GetInvoiceType() string {
	if x != nil {
		return x.InvoiceType
	}
	return ""
}

func (x *ConsultDownloadRequest) GetInvoiceStatus() InvoiceStatus {
	if x != nil {
		return x.InvoiceStatus
	}
	return InvoiceStatus_INVOICE_STATUS_UNSPECIFIED
}

func (x *ConsultDownloadRequest) GetThirdPartyRfc() string {
	if x != nil {
		return x.ThirdPartyRfc
	}
	return ""
}

func (x *ConsultDownloadRequest) GetComplemento() string {
	if x != nil {
		return x.Complemento
	}
	return ""
}

func (x *ConsultDownloadRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ConsultDownloadRequest) GetCredentialRef() *CredentialRef {
	if x != nil {
		return x.CredentialRef
	}
	return nil
}

type ConsultDownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SatStatusCode string                 `protobuf:"bytes,1,opt,name=sat_status_code,json=satStatusCode,proto3" json:"sat_status_code,omitempty"`
	SatMessage    string                 `protobuf:"bytes,2,opt,name=sat_message,json=satMessage,proto3" json:"sat_message,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultDownloadResponse) Reset() {
	*x = ConsultDownloadResponse{}
	mi := &file_satcfdi_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultDownloadResponse) ProtoMessage() {}

func (x *ConsultDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_satcfdi_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultDownloadResponse.ProtoReflect.Descriptor instead.
func (*ConsultDownloadResponse) Descriptor() ([]byte, []int) {
	return file_satcfdi_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *ConsultDownloadResponse) GetSatStatusCode() string {
	if x != nil {
		return x.SatStatusCode
	}
	return ""
}

func (x *ConsultDownloadResponse) GetSatMessage() string {
	if x != nil {
		return x.SatMessage
	}
	return ""
}

func (x *ConsultDownloadResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type VerifyDownloadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Credentials    *SATCredentials        `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	AccessToken    string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RfcSolicitante string                 `protobuf:"bytes,3,opt,name=rfc_solicitante,json=rfcSolicitante,proto3" json:"rfc_solicitante,omitempty"`
	RequestId      string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CredentialRef  *CredentialRef         `protobuf:"bytes,5,opt,name=credential_ref,json=credentialRef,proto3" json:"credential_ref,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyDownloadRequest) Reset() {
	*x = VerifyDownloadRequest{}
	mi := &file_satcfdi_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyDownloadRequest) ProtoMessage() {}

func (x *VerifyDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_satcfdi_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyDownloadRequest.ProtoReflect.Descriptor instead.
func (*VerifyDownloadRequest) Descriptor() ([]byte, []int) {
	return file_satcfdi_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyDownloadRequest) GetCredentials() *SATCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *VerifyDownloadRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *VerifyDownloadRequest) GetRfcSolicitante() string {
	if x != nil {
		return x.RfcSolicitante
	}
	return ""
}

func (x *VerifyDownloadRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *VerifyDownloadRequest) GetCredentialRef() *CredentialRef {
	if x != nil {
		return x.CredentialRef
	}
	return nil
}

type VerifyDownloadResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SatStatusCode     string                 `protobuf:"bytes,1,opt,name=sat_status_code,json=satStatusCode,proto3" json:"sat_status_code,omitempty"`
	RequestStatus     DownloadRequestStatus  `protobuf:"varint,2,opt,name=request_status,json=requestStatus,proto3,enum=satcfdi.v1.DownloadRequestStatus" json:"request_status,omitempty"`
	RequestStatusCode string                 `protobuf:"bytes,3,opt,name=request_status_code,json=requestStatusCode,proto3" json:"request_status_code,omitempty"`
	CfdiCount         int32                  `protobuf:"varint,4,opt,name=cfdi_count,json=cfdiCount,proto3" json:"cfdi_count,omitempty"`
	SatMessage        string                 `protobuf:"bytes,5,opt,name=sat_message,json=satMessage,proto3" json:"sat_message,omitempty"`
	PackageIds        []string               `protobuf:"bytes,6,rep,name=package_ids,json=packageIds,proto3" json:"package_ids,omitempty"`
	RawRequestStatus  int32                  `protobuf:"varint,7,opt,name=raw_request_status,json=rawRequestStatus,proto3" json:"raw_request_status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VerifyDownloadResponse) Reset() {
	*x = VerifyDownloadResponse{}
	mi := &file_satcfdi_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyDownloadResponse) ProtoMessage() {}

func (x *VerifyDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_satcfdi_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyDownloadResponse.ProtoReflect.Descriptor instead.
func (*VerifyDownloadResponse) Descriptor() ([]byte, []int) {
	return file_satcfdi_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyDownloadResponse) GetSatStatusCode() string {
	if x != nil {
		return x.SatStatusCode
	}
	return ""
}

func (x *VerifyDownloadResponse) GetRequestStatus() DownloadRequestStatus {
	if x != nil {
		return x.RequestStatus
	}
	return DownloadRequestStatus_DOWNLOAD_REQUEST_STATUS_UNSPECIFIED
}

func (x *VerifyDownloadResponse) GetRequestStatusCode() string {
	if x != nil {
		return x.RequestStatusCode
	}
	return ""
}

func (x *VerifyDownloadResponse) GetCfdiCount() int32 {
	if x != nil {
		return x.CfdiCount
	}
	return 0
}

func (x *VerifyDownloadResponse) GetSatMessage() string {
	if x != nil {
		return x.SatMessage
	}
	return ""
}

func (x *VerifyDownloadResponse) GetPackageIds() []string {
	if x != nil {
		return x.PackageIds
	}
	return nil
}

func (x *VerifyDownloadResponse) GetRawRequestStatus() int32 {
	if x != nil {
		return x.RawRequestStatus
	}
	return 0
}

type DownloadPackageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Credentials    *SATCredentials        `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	AccessToken    string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RfcSolicitante string                 `protobuf:"bytes,3,opt,name=rfc_solicitante,json=rfcSolicitante,proto3" json:"rfc_solicitante,omitempty"`
	PackageId      string                 `protobuf:"bytes,4,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	CredentialRef  *CredentialRef         `protobuf:"bytes,5,opt,name=credential_ref,json=credentialRef,proto3" json:"credential_ref,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DownloadPackageRequest) Reset() {
	*x = DownloadPackageRequest{}
	mi := &file_satcfdi_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadPackageRequest) ProtoMessage() {}

func (x *DownloadPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_satcfdi_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadPackageRequest.ProtoReflect.Descriptor instead.
func (*DownloadPackageRequest) Descriptor() ([]byte, []int) {
	return file_satcfdi_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *DownloadPackageRequest) GetCredentials() *SATCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *DownloadPackageRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *DownloadPackageRequest) GetRfcSolicitante() string {
	if x != nil {
		return x.RfcSolicitante
	}
	return ""
}

func (x *DownloadPackageRequest) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *DownloadPackageRequest) GetCredentialRef() *CredentialRef {
	if x != nil {
		return x.CredentialRef
	}
	return nil
}

type DownloadPackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SatStatusCode string                 `protobuf:"bytes,1,opt,name=sat_status_code,json=satStatusCode,proto3" json:"sat_status_code,omitempty"`
	SatMessage    string                 `protobuf:"bytes,2,opt,name=sat_message,json=satMessage,proto3" json:"sat_message,omitempty"`
	PackageId     string                 `protobuf:"bytes,3,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	PackageBase64 string                 `protobuf:"bytes,4,opt,name=package_base64,json=packageBase64,proto3" json:"package_base64,omitempty"`
	PackageBytes  []byte                 `protobuf:"bytes,5,opt,name=package_bytes,json=packageBytes,proto3" json:"package_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadPackageResponse) Reset() {
	*x = DownloadPackageResponse{}
	mi := &file_satcfdi_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadPackageResponse) ProtoMessage() {}

func (x *DownloadPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_satcfdi_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadPackageResponse.ProtoReflect.Descriptor instead.
func (*DownloadPackageResponse) Descriptor() ([]byte, []int) {
	return file_satcfdi_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *DownloadPackageResponse) GetSatStatusCode() string {
	if x != nil {
		return x.SatStatusCode
	}
	return ""
}

func (x *DownloadPackageResponse) GetSatMessage() string {
	if x != nil {
		return x.SatMessage
	}
	return ""
}

func (x *DownloadPackageResponse) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *DownloadPackageResponse) GetPackageBase64() string {
	if x != nil {
		return x.PackageBase64
	}
	return ""
}

func (x *DownloadPackageResponse) GetPackageBytes() []byte {
	if x != nil {
		return x.PackageBytes
	}
	return nil
}

type StreamDownloadPackageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Credentials    *SATCredentials        `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	AccessToken    string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RfcSolicitante string                 `protobuf:"bytes,3,opt,name=rfc_solicitante,json=rfcSolicitante,proto3" json:"rfc_solicitante,omitempty"`
	PackageId      string                 `protobuf:"bytes,4,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	CredentialRef  *CredentialRef         `protobuf:"bytes,5,opt,name=credential_ref,json=credentialRef,proto3" json:"credential_ref,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamDownloadPackageRequest) Reset() {
	*x = StreamDownloadPackageRequest{}
	mi := &file_satcfdi_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDownloadPackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDownloadPackageRequest) ProtoMessage() {}

func (x *StreamDownloadPackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_satcfdi_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDownloadPackageRequest.ProtoReflect.Descriptor instead.
func (*StreamDownloadPackageRequest) Descriptor() ([]byte, []int) {
	return file_satcfdi_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *StreamDownloadPackageRequest) GetCredentials() *SATCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *StreamDownloadPackageRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *StreamDownloadPackageRequest) GetRfcSolicitante() string {
	if x != nil {
		return x.RfcSolicitante
	}
	return ""
}

func (x *StreamDownloadPackageRequest) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *StreamDownloadPackageRequest) GetCredentialRef() *CredentialRef {
	if x != nil {
		return x.CredentialRef
	}
	return nil
}

type StreamDownloadPackageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageId     string                 `protobuf:"bytes,1,opt,name=package_id,json=packageId,proto3" json:"package_id,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,4,opt,name=eof,proto3" json:"eof,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,5,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	SatStatusCode string                 `protobuf:"bytes,6,opt,name=sat_status_code,json=satStatusCode,proto3" json:"sat_status_code,omitempty"`
	SatMessage    string                 `protobuf:"bytes,7,opt,name=sat_message,json=satMessage,proto3" json:"sat_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamDownloadPackageResponse) Reset() {
	*x = StreamDownloadPackageResponse{}
	mi := &file_satcfdi_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamDownloadPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamDownloadPackageResponse) ProtoMessage() {}

func (x *StreamDownloadPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_satcfdi_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamDownloadPackageResponse.ProtoReflect.Descriptor instead.
func (*StreamDownloadPackageResponse) Descriptor() ([]byte, []int) {
	return file_satcfdi_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *StreamDownloadPackageResponse) GetPackageId() string {
	if x != nil {
		return x.PackageId
	}
	return ""
}

func (x *StreamDownloadPackageResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *StreamDownloadPackageResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamDownloadPackageResponse) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

func (x *StreamDownloadPackageResponse) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *StreamDownloadPackageResponse) GetSatStatusCode() string {
	if x != nil {
		return x.SatStatusCode
	}
	return ""
}

func (x *StreamDownloadPackageResponse) GetSatMessage() string {
	if x != nil {
		return x.SatMessage
	}
	return ""
}

type PollPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interval      *durationpb.Duration   `protobuf:"bytes,1,opt,name=interval,proto3" json:"interval,omitempty"`
	MaxAttempts   int32                  `protobuf:"varint,2,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollPolicy) Reset() {
	*x = PollPolicy{}
	mi := &file_satcfdi_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollPolicy) ProtoMessage() {}

func (x *PollPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_satcfdi_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollPolicy.ProtoReflect.Descriptor instead.
func (*PollPolicy) Descriptor() ([]byte, []int) {
	return file_satcfdi_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *PollPolicy) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *PollPolicy) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

type RunDownloadFlowRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Credentials    *SATCredentials        `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	CredentialRef  *CredentialRef         `protobuf:"bytes,2,opt,name=credential_ref,json=credentialRef,proto3" json:"credential_ref,omitempty"`
	RfcSolicitante string                 `protobuf:"bytes,3,opt,name=rfc_solicitante,json=rfcSolicitante,proto3" json:"rfc_solicitante,omitempty"`
	FechaInicial   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=fecha_inicial,json=fechaInicial,proto3" json:"fecha_inicial,omitempty"`
	FechaFinal     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=fecha_final,json=fechaFinal,proto3" json:"fecha_final,omitempty"`
	DownloadType   DownloadType           `protobuf:"varint,6,opt,name=download_type,json=downloadType,proto3,enum=satcfdi.v1.DownloadType" json:"download_type,omitempty"`
	QueryType      QueryType              `protobuf:"varint,7,opt,name=query_type,json=queryType,proto3,enum=satcfdi.v1.QueryType" json:"query_type,omitempty"`
	CounterpartRfc []string               `protobuf:"bytes,8,rep,name=counterpart_rfc,json=counterpartRfc,proto3" json:"counterpart_rfc,omitempty"`
	InvoiceType    string                 `protobuf:"bytes,9,opt,name=invoice_type,json=invoiceType,proto3" json:"invoice_type,omitempty"`
	InvoiceStatus  InvoiceStatus          `protobuf:"varint,10,opt,name=invoice_status,json=invoiceStatus,proto3,enum=satcfdi.v1.InvoiceStatus" json:"invoice_status,omitempty"`
	ThirdPartyRfc  string                 `protobuf:"bytes,11,opt,name=third_party_rfc,json=thirdPartyRfc,proto3" json:"third_party_rfc,omitempty"`
	Complemento    string                 `protobuf:"bytes,12,opt,name=complemento,proto3" json:"complemento,omitempty"`
	Uuid           string                 `protobuf:"bytes,13,opt,name=uuid,proto3" json:"uuid,omitempty"`
	PollPolicy     *PollPolicy            `protobuf:"bytes,14,opt,name=poll_policy,json=pollPolicy,proto3" json:"poll_policy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunDownloadFlowRequest) Reset() {
	*x = RunDownloadFlowRequest{}
	mi := &file_satcfdi_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunDownloadFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunDownloadFlowRequest) ProtoMessage() {}

func (x *RunDownloadFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_satcfdi_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunDownloadFlowRequest.ProtoReflect.Descriptor instead.
func (*RunDownloadFlowRequest) Descriptor() ([]byte, []int) {
	return file_satcfdi_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *RunDownloadFlowRequest) GetCredentials() *SATCredentials {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *RunDownloadFlowRequest) GetCredentialRef() *CredentialRef {
	if x != nil {
		return x.CredentialRef
	}
	return nil
}

func (x *RunDownloadFlowRequest) GetRfcSolicitante() string {
	if x != nil {
		return x.RfcSolicitante
	}
	return ""
}

func (x *RunDownloadFlowRequest) GetFechaInicial() *timestamppb.Timestamp {
	if x != nil {
		return x.FechaInicial
	}
	return nil
}

func (x *RunDownloadFlowRequest) GetFechaFinal() *timestamppb.Timestamp {
	if x != nil {
		return x.FechaFinal
	}
	return nil
}

func (x *RunDownloadFlowRequest) GetDownloadType() DownloadType {
	if x != nil {
		return x.DownloadType
	}
	return DownloadType_DOWNLOAD_TYPE_UNSPECIFIED
}

func (x *RunDownloadFlowRequest) GetQueryType() QueryType {
	if x != nil {
		return x.QueryType
	}
	return QueryType_QUERY_TYPE_UNSPECIFIED
}

func (x *RunDownloadFlowRequest) GetCounterpartRfc() []string {
	if x != nil {
		return x.CounterpartRfc
	}
	return nil
}

func (x *RunDownloadFlowRequest) GetInvoiceType() string {
	if x != nil {
		return x.InvoiceType
	}
	return ""
}

func (x *RunDownloadFlowRequest) GetInvoiceStatus() InvoiceStatus {
	if x != nil {
		return x.InvoiceStatus
	}
	return InvoiceStatus_INVOICE_STATUS_UNSPECIFIED
}

func (x *RunDownloadFlowRequest) GetThirdPartyRfc() string {
	if x != nil {
		return x.ThirdPartyRfc
	}
	return ""
}

func (x *RunDownloadFlowRequest) GetComplemento() string {
	if x != nil {
		return x.Complemento
	}
	return ""
}

func (x *RunDownloadFlowRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *RunDownloadFlowRequest) GetPollPolicy() *PollPolicy {
	if x != nil {
		return x.PollPolicy
	}
	return nil
}

type RunDownloadFlowResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RequestId           string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SubmitSatStatusCode string                 `protobuf:"bytes,2,opt,name=submit_sat_status_code,json=submitSatStatusCode,proto3" json:"submit_sat_status_code,omitempty"`
	SubmitSatMessage    string                 `protobuf:"bytes,3,opt,name=submit_sat_message,json=submitSatMessage,proto3" json:"submit_sat_message,omitempty"`
	VerifySatStatusCode string                 `protobuf:"bytes,4,opt,name=verify_sat_status_code,json=verifySatStatusCode,proto3" json:"verify_sat_status_code,omitempty"`
	RequestStatus       DownloadRequestStatus  `protobuf:"varint,5,opt,name=request_status,json=requestStatus,proto3,enum=satcfdi.v1.DownloadRequestStatus" json:"request_status,omitempty"`
	RequestStatusCode   string                 `protobuf:"bytes,6,opt,name=request_status_code,json=requestStatusCode,proto3" json:"request_status_code,omitempty"`
	CfdiCount           int32                  `protobuf:"varint,7,opt,name=cfdi_count,json=cfdiCount,proto3" json:"cfdi_count,omitempty"`
	VerifySatMessage    string                 `protobuf:"bytes,8,opt,name=verify_sat_message,json=verifySatMessage,proto3" json:"verify_sat_message,omitempty"`
	PackageIds          []string               `protobuf:"bytes,9,rep,name=package_ids,json=packageIds,proto3" json:"package_ids,omitempty"`
	RawRequestStatus    int32                  `protobuf:"varint,10,opt,name=raw_request_status,json=rawRequestStatus,proto3" json:"raw_request_status,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RunDownloadFlowResponse) Reset() {
	*x = RunDownloadFlowResponse{}
	mi := &file_satcfdi_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunDownloadFlowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunDownloadFlowResponse) ProtoMessage() {}

func (x *RunDownloadFlowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_satcfdi_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunDownloadFlowResponse.ProtoReflect.Descriptor instead.
func (*RunDownloadFlowResponse) Descriptor() ([]byte, []int) {
	return file_satcfdi_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *RunDownloadFlowResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RunDownloadFlowResponse) GetSubmitSatStatusCode() string {
	if x != nil {
		return x.SubmitSatStatusCode
	}
	return ""
}

func (x *RunDownloadFlowResponse) GetSubmitSatMessage() string {
	if x != nil {
		return x.SubmitSatMessage
	}
	return ""
}

func (x *RunDownloadFlowResponse) GetVerifySatStatusCode() string {
	if x != nil {
		return x.VerifySatStatusCode
	}
	return ""
}

func (x *RunDownloadFlowResponse) GetRequestStatus() DownloadRequestStatus {
	if x != nil {
		return x.RequestStatus
	}
	return DownloadRequestStatus_DOWNLOAD_REQUEST_STATUS_UNSPECIFIED
}

func (x *RunDownloadFlowResponse) GetRequestStatusCode() string {
	if x != nil {
		return x.RequestStatusCode
	}
	return ""
}

func (x *RunDownloadFlowResponse) GetCfdiCount() int32 {
	if x != nil {
		return x.CfdiCount
	}
	return 0
}

func (x *RunDownloadFlowResponse) GetVerifySatMessage() string {
	if x != nil {
		return x.VerifySatMessage
	}
	return ""
}

func (x *RunDownloadFlowResponse) GetPackageIds() []string {
	if x != nil {
		return x.PackageIds
	}
	return nil
}

func (x *RunDownloadFlowResponse) GetRawRequestStatus() int32 {
	if x != nil {
		return x.RawRequestStatus
	}
	return 0
}

type ValidateCfdiRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RfcEmisor     string                 `protobuf:"bytes,1,opt,name=rfc_emisor,json=rfcEmisor,proto3" json:"rfc_emisor,omitempty"`
	RfcReceptor   string                 `protobuf:"bytes,2,opt,name=rfc_receptor,json=rfcReceptor,proto3" json:"rfc_receptor,omitempty"`
	Total         string                 `protobuf:"bytes,3,opt,name=total,proto3" json:"total,omitempty"`
	Uuid          string                 `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCfdiRequest) Reset() {
	*x = ValidateCfdiRequest{}
	mi := &file_satcfdi_v1_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCfdiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCfdiRequest) ProtoMessage() {}

func (x *ValidateCfdiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_satcfdi_v1_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCfdiRequest.ProtoReflect.Descriptor instead.
func (*ValidateCfdiRequest) Descriptor() ([]byte, []int) {
	return file_satcfdi_v1_service_proto_rawDescGZIP(), []int{16}
}

func (x *ValidateCfdiRequest) GetRfcEmisor() string {
	if x != nil {
		return x.RfcEmisor
	}
	return ""
}

func (x *ValidateCfdiRequest) GetRfcReceptor() string {
	if x != nil {
		return x.RfcReceptor
	}
	return ""
}

func (x *ValidateCfdiRequest) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

func (x *ValidateCfdiRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ValidateCfdiResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CodigoEstatus string                 `protobuf:"bytes,1,opt,name=codigo_estatus,json=codigoEstatus,proto3" json:"codigo_estatus,omitempty"`
	EsCancelable  string                 `protobuf:"bytes,2,opt,name=es_cancelable,json=esCancelable,proto3" json:"es_cancelable,omitempty"`
	Estado        string                 `protobuf:"bytes,3,opt,name=estado,proto3" json:"estado,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCfdiResponse) Reset() {
	*x = ValidateCfdiResponse{}
	mi := &file_satcfdi_v1_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCfdiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCfdiResponse) ProtoMessage() {}

func (x *ValidateCfdiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_satcfdi_v1_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCfdiResponse.ProtoReflect.Descriptor instead.
func (*ValidateCfdiResponse) Descriptor() ([]byte, []int) {
	return file_satcfdi_v1_service_proto_rawDescGZIP(), []int{17}
}

func (x *ValidateCfdiResponse) GetCodigoEstatus() string {
	if x != nil {
		return x.CodigoEstatus
	}
	return ""
}

func (x *ValidateCfdiResponse) GetEsCancelable() string {
	if x != nil {
		return x.EsCancelable
	}
	return ""
}

func (x *ValidateCfdiResponse) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

var File_satcfdi_v1_service_proto protoreflect.FileDescriptor

const file_satcfdi_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x18satcfdi/v1/service.proto\x12\n" +
	"satcfdi.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x93\x01\n" +
	"\x0eSATCredentials\x12'\n" +
	"\x0fcertificate_der\x18\x01 \x01(\fR\x0ecertificateDer\x12&\n" +
	"\x0fprivate_key_der\x18\x02 \x01(\fR\rprivateKeyDer\x120\n" +
	"\x14private_key_password\x18\x03 \x01(\tR\x12privateKeyPassword\";\n" +
	"\rCredentialRef\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\xaf\x03\n" +
	"\x12ServiceErrorDetail\x125\n" +
	"\bcategory\x18\x01 \x01(\x0e2\x19.satcfdi.v1.ErrorCategoryR\bcategory\x12\x19\n" +
	"\bsat_code\x18\x02 \x01(\tR\asatCode\x12\x1f\n" +
	"\vsat_message\x18\x03 \x01(\tR\n" +
	"satMessage\x12(\n" +
	"\x10soap_http_status\x18\x04 \x01(\x05R\x0esoapHttpStatus\x12*\n" +
	"\x11soap_fault_string\x18\x05 \x01(\tR\x0fsoapFaultString\x12\x1c\n" +
	"\tretryable\x18\x06 \x01(\bR\tretryable\x12\x1c\n" +
	"\toperation\x18\a \x01(\tR\toperation\x12\x1d\n" +
	"\n" +
	"request_id\x18\b \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"package_id\x18\t \x01(\tR\tpackageId\x12&\n" +
	"\x0fsat_status_code\x18\n" +
	" \x01(\tR\rsatStatusCode\x12.\n" +
	"\x13request_status_code\x18\v \x01(\tR\x11requestStatusCode\"\x95\x01\n" +
	"\x13AuthenticateRequest\x12<\n" +
	"\vcredentials\x18\x01 \x01(\v2\x1a.satcfdi.v1.SATCredentialsR\vcredentials\x12@\n" +
	"\x0ecredential_ref\x18\x02 \x01(\v2\x19.satcfdi.v1.CredentialRefR\rcredentialRef\"9\n" +
	"\x14AuthenticateResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\xc3\x05\n" +
	"\x16ConsultDownloadRequest\x12<\n" +
	"\vcredentials\x18\x01 \x01(\v2\x1a.satcfdi.v1.SATCredentialsR\vcredentials\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12'\n" +
	"\x0frfc_solicitante\x18\x03 \x01(\tR\x0erfcSolicitante\x12?\n" +
	"\rfecha_inicial\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ffechaInicial\x12;\n" +
	"\vfecha_final\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"fechaFinal\x12=\n" +
	"\rdownload_type\x18\x06 \x01(\x0e2\x18.satcfdi.v1.DownloadTypeR\fdownloadType\x124\n" +
	"\n" +
	"query_type\x18\a \x01(\x0e2\x15.satcfdi.v1.QueryTypeR\tqueryType\x12'\n" +
	"\x0fcounterpart_rfc\x18\b \x03(\tR\x0ecounterpartRfc\x12!\n" +
	"\finvoice_type\x18\t \x01(\tR\vinvoiceType\x12@\n" +
	"\x0einvoice_status\x18\n" +
	" \x01(\x0e2\x19.satcfdi.v1.InvoiceStatusR\rinvoiceStatus\x12&\n" +
	"\x0fthird_party_rfc\x18\v \x01(\tR\rthirdPartyRfc\x12 \n" +
	"\vcomplemento\x18\f \x01(\tR\vcomplemento\x12\x12\n" +
	"\x04uuid\x18\r \x01(\tR\x04uuid\x12@\n" +
	"\x0ecredential_ref\x18\x0e \x01(\v2\x19.satcfdi.v1.CredentialRefR\rcredentialRef\"\x81\x01\n" +
	"\x17ConsultDownloadResponse\x12&\n" +
	"\x0fsat_status_code\x18\x01 \x01(\tR\rsatStatusCode\x12\x1f\n" +
	"\vsat_message\x18\x02 \x01(\tR\n" +
	"satMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"\x82\x02\n" +
	"\x15VerifyDownloadRequest\x12<\n" +
	"\vcredentials\x18\x01 \x01(\v2\x1a.satcfdi.v1.SATCredentialsR\vcredentials\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12'\n" +
	"\x0frfc_solicitante\x18\x03 \x01(\tR\x0erfcSolicitante\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12@\n" +
	"\x0ecredential_ref\x18\x05 \x01(\v2\x19.satcfdi.v1.CredentialRefR\rcredentialRef\"\xc9\x02\n" +
	"\x16VerifyDownloadResponse\x12&\n" +
	"\x0fsat_status_code\x18\x01 \x01(\tR\rsatStatusCode\x12H\n" +
	"\x0erequest_status\x18\x02 \x01(\x0e2!.satcfdi.v1.DownloadRequestStatusR\rrequestStatus\x12.\n" +
	"\x13request_status_code\x18\x03 \x01(\tR\x11requestStatusCode\x12\x1d\n" +
	"\n" +
	"cfdi_count\x18\x04 \x01(\x05R\tcfdiCount\x12\x1f\n" +
	"\vsat_message\x18\x05 \x01(\tR\n" +
	"satMessage\x12\x1f\n" +
	"\vpackage_ids\x18\x06 \x03(\tR\n" +
	"packageIds\x12,\n" +
	"\x12raw_request_status\x18\a \x01(\x05R\x10rawRequestStatus\"\x83\x02\n" +
	"\x16DownloadPackageRequest\x12<\n" +
	"\vcredentials\x18\x01 \x01(\v2\x1a.satcfdi.v1.SATCredentialsR\vcredentials\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12'\n" +
	"\x0frfc_solicitante\x18\x03 \x01(\tR\x0erfcSolicitante\x12\x1d\n" +
	"\n" +
	"package_id\x18\x04 \x01(\tR\tpackageId\x12@\n" +
	"\x0ecredential_ref\x18\x05 \x01(\v2\x19.satcfdi.v1.CredentialRefR\rcredentialRef\"\xcd\x01\n" +
	"\x17DownloadPackageResponse\x12&\n" +
	"\x0fsat_status_code\x18\x01 \x01(\tR\rsatStatusCode\x12\x1f\n" +
	"\vsat_message\x18\x02 \x01(\tR\n" +
	"satMessage\x12\x1d\n" +
	"\n" +
	"package_id\x18\x03 \x01(\tR\tpackageId\x12%\n" +
	"\x0epackage_base64\x18\x04 \x01(\tR\rpackageBase64\x12#\n" +
	"\rpackage_bytes\x18\x05 \x01(\fR\fpackageBytes\"\x89\x02\n" +
	"\x1cStreamDownloadPackageRequest\x12<\n" +
	"\vcredentials\x18\x01 \x01(\v2\x1a.satcfdi.v1.SATCredentialsR\vcredentials\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12'\n" +
	"\x0frfc_solicitante\x18\x03 \x01(\tR\x0erfcSolicitante\x12\x1d\n" +
	"\n" +
	"package_id\x18\x04 \x01(\tR\tpackageId\x12@\n" +
	"\x0ecredential_ref\x18\x05 \x01(\v2\x19.satcfdi.v1.CredentialRefR\rcredentialRef\"\xe6\x01\n" +
	"\x1dStreamDownloadPackageResponse\x12\x1d\n" +
	"\n" +
	"package_id\x18\x01 \x01(\tR\tpackageId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x04 \x01(\bR\x03eof\x12\x1f\n" +
	"\vtotal_bytes\x18\x05 \x01(\x03R\n" +
	"totalBytes\x12&\n" +
	"\x0fsat_status_code\x18\x06 \x01(\tR\rsatStatusCode\x12\x1f\n" +
	"\vsat_message\x18\a \x01(\tR\n" +
	"satMessage\"f\n" +
	"\n" +
	"PollPolicy\x125\n" +
	"\binterval\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\binterval\x12!\n" +
	"\fmax_attempts\x18\x02 \x01(\x05R\vmaxAttempts\"\xd9\x05\n" +
	"\x16RunDownloadFlowRequest\x12<\n" +
	"\vcredentials\x18\x01 \x01(\v2\x1a.satcfdi.v1.SATCredentialsR\vcredentials\x12@\n" +
	"\x0ecredential_ref\x18\x02 \x01(\v2\x19.satcfdi.v1.CredentialRefR\rcredentialRef\x12'\n" +
	"\x0frfc_solicitante\x18\x03 \x01(\tR\x0erfcSolicitante\x12?\n" +
	"\rfecha_inicial\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ffechaInicial\x12;\n" +
	"\vfecha_final\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"fechaFinal\x12=\n" +
	"\rdownload_type\x18\x06 \x01(\x0e2\x18.satcfdi.v1.DownloadTypeR\fdownloadType\x124\n" +
	"\n" +
	"query_type\x18\a \x01(\x0e2\x15.satcfdi.v1.QueryTypeR\tqueryType\x12'\n" +
	"\x0fcounterpart_rfc\x18\b \x03(\tR\x0ecounterpartRfc\x12!\n" +
	"\finvoice_type\x18\t \x01(\tR\vinvoiceType\x12@\n" +
	"\x0einvoice_status\x18\n" +
	" \x01(\x0e2\x19.satcfdi.v1.InvoiceStatusR\rinvoiceStatus\x12&\n" +
	"\x0fthird_party_rfc\x18\v \x01(\tR\rthirdPartyRfc\x12 \n" +
	"\vcomplemento\x18\f \x01(\tR\vcomplemento\x12\x12\n" +
	"\x04uuid\x18\r \x01(\tR\x04uuid\x127\n" +
	"\vpoll_policy\x18\x0e \x01(\v2\x16.satcfdi.v1.PollPolicyR\n" +
	"pollPolicy\"\xe6\x03\n" +
	"\x17RunDownloadFlowResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x123\n" +
	"\x16submit_sat_status_code\x18\x02 \x01(\tR\x13submitSatStatusCode\x12,\n" +
	"\x12submit_sat_message\x18\x03 \x01(\tR\x10submitSatMessage\x123\n" +
	"\x16verify_sat_status_code\x18\x04 \x01(\tR\x13verifySatStatusCode\x12H\n" +
	"\x0erequest_status\x18\x05 \x01(\x0e2!.satcfdi.v1.DownloadRequestStatusR\rrequestStatus\x12.\n" +
	"\x13request_status_code\x18\x06 \x01(\tR\x11requestStatusCode\x12\x1d\n" +
	"\n" +
	"cfdi_count\x18\a \x01(\x05R\tcfdiCount\x12,\n" +
	"\x12verify_sat_message\x18\b \x01(\tR\x10verifySatMessage\x12\x1f\n" +
	"\vpackage_ids\x18\t \x03(\tR\n" +
	"packageIds\x12,\n" +
	"\x12raw_request_status\x18\n" +
	" \x01(\x05R\x10rawRequestStatus\"\x81\x01\n" +
	"\x13ValidateCfdiRequest\x12\x1d\n" +
	"\n" +
	"rfc_emisor\x18\x01 \x01(\tR\trfcEmisor\x12!\n" +
	"\frfc_receptor\x18\x02 \x01(\tR\vrfcReceptor\x12\x14\n" +
	"\x05total\x18\x03 \x01(\tR\x05total\x12\x12\n" +
	"\x04uuid\x18\x04 \x01(\tR\x04uuid\"z\n" +
	"\x14ValidateCfdiResponse\x12%\n" +
	"\x0ecodigo_estatus\x18\x01 \x01(\tR\rcodigoEstatus\x12#\n" +
	"\res_cancelable\x18\x02 \x01(\tR\fesCancelable\x12\x16\n" +
	"\x06estado\x18\x03 \x01(\tR\x06estado*f\n" +
	"\fDownloadType\x12\x1d\n" +
	"\x19DOWNLOAD_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17DOWNLOAD_TYPE_RECIBIDOS\x10\x01\x12\x1a\n" +
	"\x16DOWNLOAD_TYPE_EMITIDOS\x10\x02*U\n" +
	"\tQueryType\x12\x1a\n" +
	"\x16QUERY_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fQUERY_TYPE_CFDI\x10\x01\x12\x17\n" +
	"\x13QUERY_TYPE_METADATA\x10\x02*\x81\x01\n" +
	"\rInvoiceStatus\x12\x1e\n" +
	"\x1aINVOICE_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12INVOICE_STATUS_ALL\x10\x01\x12\x1a\n" +
	"\x16INVOICE_STATUS_VIGENTE\x10\x02\x12\x1c\n" +
	"\x18INVOICE_STATUS_CANCELADO\x10\x03*\xce\x02\n" +
	"\x15DownloadRequestStatus\x12'\n" +
	"#DOWNLOAD_REQUEST_STATUS_UNSPECIFIED\x10\x00\x12$\n" +
	" DOWNLOAD_REQUEST_STATUS_ACCEPTED\x10\x01\x12'\n" +
	"#DOWNLOAD_REQUEST_STATUS_IN_PROGRESS\x10\x02\x12$\n" +
	" DOWNLOAD_REQUEST_STATUS_FINISHED\x10\x03\x12!\n" +
	"\x1dDOWNLOAD_REQUEST_STATUS_ERROR\x10\x04\x12$\n" +
	" DOWNLOAD_REQUEST_STATUS_REJECTED\x10\x05\x12#\n" +
	"\x1fDOWNLOAD_REQUEST_STATUS_EXPIRED\x10\x06\x12)\n" +
	"%DOWNLOAD_REQUEST_STATUS_TOKEN_INVALID\x10\a*\x9e\x02\n" +
	"\rErrorCategory\x12\x1e\n" +
	"\x1aERROR_CATEGORY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ERROR_CATEGORY_VALIDATION\x10\x01\x12\x1e\n" +
	"\x1aERROR_CATEGORY_CREDENTIALS\x10\x02\x12!\n" +
	"\x1dERROR_CATEGORY_AUTHENTICATION\x10\x03\x12\x1b\n" +
	"\x17ERROR_CATEGORY_BUSINESS\x10\x04\x12\x17\n" +
	"\x13ERROR_CATEGORY_SOAP\x10\x05\x12\x1c\n" +
	"\x18ERROR_CATEGORY_TRANSPORT\x10\x06\x12\x1b\n" +
	"\x17ERROR_CATEGORY_INTERNAL\x10\a\x12\x1a\n" +
	"\x16ERROR_CATEGORY_TIMEOUT\x10\b2\xb3\x04\n" +
	"\n" +
	"SATService\x12Q\n" +
	"\fAuthenticate\x12\x1f.satcfdi.v1.AuthenticateRequest\x1a .satcfdi.v1.AuthenticateResponse\x12Z\n" +
	"\x0fConsultDownload\x12\".satcfdi.v1.ConsultDownloadRequest\x1a#.satcfdi.v1.ConsultDownloadResponse\x12W\n" +
	"\x0eVerifyDownload\x12!.satcfdi.v1.VerifyDownloadRequest\x1a\".satcfdi.v1.VerifyDownloadResponse\x12Z\n" +
	"\x0fDownloadPackage\x12\".satcfdi.v1.DownloadPackageRequest\x1a#.satcfdi.v1.DownloadPackageResponse\x12n\n" +
	"\x15StreamDownloadPackage\x12(.satcfdi.v1.StreamDownloadPackageRequest\x1a).satcfdi.v1.StreamDownloadPackageResponse0\x01\x12Q\n" +
	"\fValidateCfdi\x12\x1f.satcfdi.v1.ValidateCfdiRequest\x1a .satcfdi.v1.ValidateCfdiResponse2l\n" +
	"\x0eSATFlowService\x12Z\n" +
	"\x0fRunDownloadFlow\x12\".satcfdi.v1.RunDownloadFlowRequest\x1a#.satcfdi.v1.RunDownloadFlowResponseBGZEgithub.com/herramientassatgobmx/go-satcfdi/proto/satcfdi/v1;satcfdiv1b\x06proto3"

var (
	file_satcfdi_v1_service_proto_rawDescOnce sync.Once
	file_satcfdi_v1_service_proto_rawDescData []byte
)

func file_satcfdi_v1_service_proto_rawDescGZIP() []byte {
	file_satcfdi_v1_service_proto_rawDescOnce.Do(func() {
		file_satcfdi_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_satcfdi_v1_service_proto_rawDesc), len(file_satcfdi_v1_service_proto_rawDesc)))
	})
	return file_satcfdi_v1_service_proto_rawDescData
}

var file_satcfdi_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_satcfdi_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_satcfdi_v1_service_proto_goTypes = []any{
	(DownloadType)(0),                     // 0: satcfdi.v1.DownloadType
	(QueryType)(0),                        // 1: satcfdi.v1.QueryType
	(InvoiceStatus)(0),                    // 2: satcfdi.v1.InvoiceStatus
	(DownloadRequestStatus)(0),            // 3: satcfdi.v1.DownloadRequestStatus
	(ErrorCategory)(0),                    // 4: satcfdi.v1.ErrorCategory
	(*SATCredentials)(nil),                // 5: satcfdi.v1.SATCredentials
	(*CredentialRef)(nil),                 // 6: satcfdi.v1.CredentialRef
	(*ServiceErrorDetail)(nil),            // 7: satcfdi.v1.ServiceErrorDetail
	(*AuthenticateRequest)(nil),           // 8: satcfdi.v1.AuthenticateRequest
	(*AuthenticateResponse)(nil),          // 9: satcfdi.v1.AuthenticateResponse
	(*ConsultDownloadRequest)(nil),        // 10: satcfdi.v1.ConsultDownloadRequest
	(*ConsultDownloadResponse)(nil),       // 11: satcfdi.v1.ConsultDownloadResponse
	(*VerifyDownloadRequest)(nil),         // 12: satcfdi.v1.VerifyDownloadRequest
	(*VerifyDownloadResponse)(nil),        // 13: satcfdi.v1.VerifyDownloadResponse
	(*DownloadPackageRequest)(nil),        // 14: satcfdi.v1.DownloadPackageRequest
	(*DownloadPackageResponse)(nil),       // 15: satcfdi.v1.DownloadPackageResponse
	(*StreamDownloadPackageRequest)(nil),  // 16: satcfdi.v1.StreamDownloadPackageRequest
	(*StreamDownloadPackageResponse)(nil), // 17: satcfdi.v1.StreamDownloadPackageResponse
	(*PollPolicy)(nil),                    // 18: satcfdi.v1.PollPolicy
	(*RunDownloadFlowRequest)(nil),        // 19: satcfdi.v1.RunDownloadFlowRequest
	(*RunDownloadFlowResponse)(nil),       // 20: satcfdi.v1.RunDownloadFlowResponse
	(*ValidateCfdiRequest)(nil),           // 21: satcfdi.v1.ValidateCfdiRequest
	(*ValidateCfdiResponse)(nil),          // 22: satcfdi.v1.ValidateCfdiResponse
	(*timestamppb.Timestamp)(nil),         // 23: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),           // 24: google.protobuf.Duration
}
var file_satcfdi_v1_service_proto_depIdxs = []int32{
	4,  // 0: satcfdi.v1.ServiceErrorDetail.category:type_name -> satcfdi.v1.ErrorCategory
	5,  // 1: satcfdi.v1.AuthenticateRequest.credentials:type_name -> satcfdi.v1.SATCredentials
	6,  // 2: satcfdi.v1.AuthenticateRequest.credential_ref:type_name -> satcfdi.v1.CredentialRef
	5,  // 3: satcfdi.v1.ConsultDownloadRequest.credentials:type_name -> satcfdi.v1.SATCredentials
	23, // 4: satcfdi.v1.ConsultDownloadRequest.fecha_inicial:type_name -> google.protobuf.Timestamp
	23, // 5: satcfdi.v1.ConsultDownloadRequest.fecha_final:type_name -> google.protobuf.Timestamp
	0,  // 6: satcfdi.v1.ConsultDownloadRequest.download_type:type_name -> satcfdi.v1.DownloadType
	1,  // 7: satcfdi.v1.ConsultDownloadRequest.query_type:type_name -> satcfdi.v1.QueryType
	2,  // 8: satcfdi.v1.ConsultDownloadRequest.invoice_status:type_name -> satcfdi.v1.InvoiceStatus
	6,  // 9: satcfdi.v1.ConsultDownloadRequest.credential_ref:type_name -> satcfdi.v1.CredentialRef
	5,  // 10: satcfdi.v1.VerifyDownloadRequest.credentials:type_name -> satcfdi.v1.SATCredentials
	6,  // 11: satcfdi.v1.VerifyDownloadRequest.credential_ref:type_name -> satcfdi.v1.CredentialRef
	3,  // 12: satcfdi.v1.VerifyDownloadResponse.request_status:type_name -> satcfdi.v1.DownloadRequestStatus
	5,  // 13: satcfdi.v1.DownloadPackageRequest.credentials:type_name -> satcfdi.v1.SATCredentials
	6,  // 14: satcfdi.v1.DownloadPackageRequest.credential_ref:type_name -> satcfdi.v1.CredentialRef
	5,  // 15: satcfdi.v1.StreamDownloadPackageRequest.credentials:type_name -> satcfdi.v1.SATCredentials
	6,  // 16: satcfdi.v1.StreamDownloadPackageRequest.credential_ref:type_name -> satcfdi.v1.CredentialRef
	24, // 17: satcfdi.v1.PollPolicy.interval:type_name -> google.protobuf.Duration
	5,  // 18: satcfdi.v1.RunDownloadFlowRequest.credentials:type_name -> satcfdi.v1.SATCredentials
	6,  // 19: satcfdi.v1.RunDownloadFlowRequest.credential_ref:type_name -> satcfdi.v1.CredentialRef
	23, // 20: satcfdi.v1.RunDownloadFlowRequest.fecha_inicial:type_name -> google.protobuf.Timestamp
	23, // 21: satcfdi.v1.RunDownloadFlowRequest.fecha_final:type_name -> google.protobuf.Timestamp
	0,  // 22: satcfdi.v1.RunDownloadFlowRequest.download_type:type_name -> satcfdi.v1.DownloadType
	1,  // 23: satcfdi.v1.RunDownloadFlowRequest.query_type:type_name -> satcfdi.v1.QueryType
	2,  // 24: satcfdi.v1.RunDownloadFlowRequest.invoice_status:type_name -> satcfdi.v1.InvoiceStatus
	18, // 25: satcfdi.v1.RunDownloadFlowRequest.poll_policy:type_name -> satcfdi.v1.PollPolicy
	3,  // 26: satcfdi.v1.RunDownloadFlowResponse.request_status:type_name -> satcfdi.v1.DownloadRequestStatus
	8,  // 27: satcfdi.v1.SATService.Authenticate:input_type -> satcfdi.v1.AuthenticateRequest
	10, // 28: satcfdi.v1.SATService.ConsultDownload:input_type -> satcfdi.v1.ConsultDownloadRequest
	12, // 29: satcfdi.v1.SATService.VerifyDownload:input_type -> satcfdi.v1.VerifyDownloadRequest
	14, // 30: satcfdi.v1.SATService.DownloadPackage:input_type -> satcfdi.v1.DownloadPackageRequest
	16, // 31: satcfdi.v1.SATService.StreamDownloadPackage:input_type -> satcfdi.v1.StreamDownloadPackageRequest
	21, // 32: satcfdi.v1.SATService.ValidateCfdi:input_type -> satcfdi.v1.ValidateCfdiRequest
	19, // 33: satcfdi.v1.SATFlowService.RunDownloadFlow:input_type -> satcfdi.v1.RunDownloadFlowRequest
	9,  // 34: satcfdi.v1.SATService.Authenticate:output_type -> satcfdi.v1.AuthenticateResponse
	11, // 35: satcfdi.v1.SATService.ConsultDownload:output_type -> satcfdi.v1.ConsultDownloadResponse
	13, // 36: satcfdi.v1.SATService.VerifyDownload:output_type -> satcfdi.v1.VerifyDownloadResponse
	15, // 37: satcfdi.v1.SATService.DownloadPackage:output_type -> satcfdi.v1.DownloadPackageResponse
	17, // 38: satcfdi.v1.SATService.StreamDownloadPackage:output_type -> satcfdi.v1.StreamDownloadPackageResponse
	22, // 39: satcfdi.v1.SATService.ValidateCfdi:output_type -> satcfdi.v1.ValidateCfdiResponse
	20, // 40: satcfdi.v1.SATFlowService.RunDownloadFlow:output_type -> satcfdi.v1.RunDownloadFlowResponse
	34, // [34:41] is the sub-list for method output_type
	27, // [27:34] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_satcfdi_v1_service_proto_init() }
func file_satcfdi_v1_service_proto_init() {
	if File_satcfdi_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_satcfdi_v1_service_proto_rawDesc), len(file_satcfdi_v1_service_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_satcfdi_v1_service_proto_goTypes,
		DependencyIndexes: file_satcfdi_v1_service_proto_depIdxs,
		EnumInfos:         file_satcfdi_v1_service_proto_enumTypes,
		MessageInfos:      file_satcfdi_v1_service_proto_msgTypes,
	}.Build()
	File_satcfdi_v1_service_proto = out.File
	file_satcfdi_v1_service_proto_goTypes = nil
	file_satcfdi_v1_service_proto_depIdxs = nil
}
